apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-0hng
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0015-tenant/tkrw-pr712-0075-0015-app/devfile-sample-0hng@sha256:aac452b66e3fc70667bb97cab8fdcb71124a5b128a5632321825b7048cd166a6
        name: my-nodejs
        resources: {}
status: {}
